# Generated by Django 3.2 on 2021-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbum',
            name='tittle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
