# Generated by Django 3.2 on 2021-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbum', '0002_allbum_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbum',
            name='tittle',
            field=models.TextField(max_length=50),
        ),
    ]
